sudo: false

os:
 - linux

language: d

before_script: cd demos

d:
 - dmd-2.086.1
 - dmd-2.085.1
 - ldc-1.16.0
 - ldc-1.15.0
 
matrix:
  fast_finish: true

env: 
  matrix:
    - ARCH=x86
    - ARCH=x86_64

addons:
  apt:
    packages:
     - gcc-multilib

script:
 - dub build --arch=$ARCH
