sudo: false

os:
 - linux
 - osx

language: d

before_script: cd demos

d:
 - dmd-2.076.0
 - ldc-1.4.0
 
matrix:
  fast_finish: true
  allow_failures:
   - d: ldc-1.4.0
     os: osx

env: 
  matrix:
    - ARCH=x86
    - ARCH=x86_64

addons:
  apt:
    packages:
     - gcc-multilib

script:
 - dub build --arch=$ARCH
